
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL DEFAULT '',
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  `remember_token` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED DEFAULT 0 NOT NULL,
  `updated_at` INT UNSIGNED DEFAULT 0 NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

